apiVersion: v1
kind: Service
metadata:
  name: flask-hello
  namespace: applications
spec:
  selector:
    app: flask-hello
  type: ClusterIP
  ports:
  - name: hello-port
    protocol: TCP
    port: 80
    targetPort: 500